services:
  - type: web
    name: attendtrack-web
    env: node
    plan: free
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: attendtrack-db
          property: connectionString
    healthCheckPath: /

databases:
  - name: attendtrack-db
    plan: free
